provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  faas-cloud-badge:
    skip_build: true
    lang: Dockerfile
    handler: ./faas-cloud-badge
    image: s8sg/faas-cloud-badge:1.0.0
    environment:
      validate_customers: "false"
      customers_url: "https://raw.githubusercontent.com/openfaas/openfaas-cloud/master/CUSTOMERS"
